[package]
name = "iris_ffmpeg"
version = "0.1.0"
authors = ["azusachino <azusachino@duck.com>"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/azusachino/iris-ffmpeg"

[dependencies]
anyhow = "1.0"

[dev-dependencies]
ffmpeg = "0.3"
